[package]
name = "bpfquery"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlparser = {version= "0.50.0", features = ["serde", "visitor"]}
lang-c = { git = "https://github.com/vickenty/lang-c.git" }
sqlparser_derive = "0.2.2"
ssh2-config = "0.2.3"
ssh2 = "0.9.4"
ssh = "0.1.4"
rustyline = "14.0.0"
