# fly.toml app configuration file generated for bpfquery on 2024-08-25T07:56:04-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bpfquery'
primary_region = 'atl'

[build]

[env]
  PORT = '8080'

[http_service]
  internal_port = 3030
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1